[package]
name = "rsrpc"
version = "0.1.0"
edition = "2018"
authors = ["spikehd"]

[lib]
name = "rsrpc"
path = "src/lib.rs"

[dependencies]
sysinfo = "0.29.8"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.105"

[[bin]]
name = "rsrpc"
path = "src/bin.rs"
