[package]
name = "rsrpc"
version = "0.4.0"
edition = "2018"
authors = ["spikehd"]

[lib]
name = "rsrpc"
path = "src/lib.rs"

[dependencies]
# binary-only
clap = { version = "4.3.21", features = ["derive"], optional = true }

# lib
async-std = "1.12.0"
sysinfo = "0.29.8"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0"
port_scanner = "0.1.5"
simple-websockets = "0.1.6"
chrono = "0.4.13"

#[cfg(target_os = "windows")]
winapi = { version = "0.3.9", features = ["namedpipeapi"] }
winapi-util = "0.1.6"

[[bin]]
name = "rsrpc"
path = "src/bin.rs"
required-features = ["clap"]

[features]
binary = ["clap"]
