[package]
name = "rsrpc"
version = "0.1.0"
edition = "2018"
authors = ["spikehd"]

[lib]
name = "rsrpc"
path = "src/lib.rs"

[dependencies]
# binary-only
clap = { version = "4.3.21", features = ["derive"], optional = true }

# lib
sysinfo = "0.29.8"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.105"
port_scanner = "0.1.5"
async-tungstenite = "0.23.0"
async-std = "1.12.0"
futures-util = "0.3.28"

[[bin]]
name = "rsrpc"
path = "src/bin.rs"
required-features = ["clap"]

[features]
binary = ["clap"]
